### ISSUE TITLE
Add names and twitter links for Broncos beat folk

### ISSUE THREAD

**Issue by githamm** [denverpost/nfl-draft-tracker#5]

**Comment by danielboniface** [comment]
@githamm I think we should replace the above-the-fold Twitter widget with a Scribblelive embed this year. We will build the Scribblelive live chat today and provide the embed code for it.

**Comment by githamm** [comment]
@danielboniface Let's give it a shot. That's how we had it set up last year but then ran into issues with Scribble being responsive on mobile so swapped it out for the Twitter feed at the last minute. Pass along the embed code and I'll play with it.
